Homework8
RomanKharitonov17/autotests_course pull request #10
Opened 2023-06-01 20:56 UTC by RomanKharitonov17

2023-06-02 20:22 UTC, vlad-vladimirovich requested changes

2023-06-02 20:22 UTC, vlad-vladimirovich commented on homework8/task_3.py
> +        return total_sum
в блоке try лучше не писать return. вынеси его в отдельный else после except

2023-06-02 20:22 UTC, vlad-vladimirovich commented on homework8/task_2.py
> +        sides = []
в целом норм. но если подумать тебе по сути список то и не нужен. если у тебя первый if проходит можно сразу объявить переменные со сторонами типа self.a, self.b, self.c = args[0], args[1], args[2] тогда не придется никаких appendОВ делать и в 36 строке получится красиво эти переменные заюзать. Можешь оставить как есть, но если есть желание можешь переделать по красоте и сразу увидишь как красивее код станет ;)

2023-06-02 20:22 UTC, vlad-vladimirovich commented on homework8/task_1.py
> +            return tuple_sum
официальная рекомендация к блоку try это что бы он выполнял только какой то кусок кода. в твоем случае конкатенация элементов кортежа. return лучше вынести в конец

2023-06-02 20:22 UTC, vlad-vladimirovich commented on homework8/task_1.py
> +        try:
а вот тут явно try лишний. как это вообще работает: в начале кода ты пишешь один try а потом все возможные исключения ловишь.

2023-06-08 09:29 UTC, maksim-obodkov approved these changes

2023-06-12 13:22 UTC, merged